[tool.poetry]
name = "mysql_app"
version = "1.0.0"
authors = [
  { name="Nikolaos Kokkos", email="nikolaoskokkos@gmail.com" },
  {name="Ioannis Tsakmakis", email="iotsakmak@gmail.com"}
]
description = "A library that allows connection to ECO1 mysql database"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
sqlalchemy = "^2.0.0"
pydantic

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
