[project]
name = "mysql_app"
version = "1.0.0"
authors = [
  { name="Nikolaos Kokkos", email="nikolaoskokkos@gmail.com" },
  {name="Ioannis Tsakmakis", email="iotsakmak@gmail.com"}
]
description = "A library that allows connection to ECO1 mysql database"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
"sqlalchemy==2.0.22",
"flask==3.0.0",
"pydantic",
"requests",
"pandas==2.1.2"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.urls]
"Homepage" = "https://github.com/itsakmak/envrio_mysql_app"
"Bug Tracker" = "https://github.com/itsakmak/envrio_mysql_app/issues"
