[project]
name = "mysql_app"
version = "1.0.0"
authors = [
  { name="Nikolaos Kokkos", email="nikolaoskokkos@gmail.com" },
]
description = "A small example package"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "sqlalchemy",
    "pydantic"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.urls]
"Homepage" = "https://github.com/itsakmak/mysql_app"
"Bug Tracker" = "https://github.com/itsakmak/mysql_app/issues"